name: unit-tests
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        sudo apt-get update -y && sudo apt-get install -y graphviz
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest -vv --cov=pydeps .

    - name: "Upload coverage to codecov.io"
      uses: codecov/codecov-action@v2.0.3
      with:
        token: ${{ secrets.CODECOV_TOKEN}}
        fail_ci_if_error: false
